version: 0.2.0
slug: remote_speaker
name: Remote Speaker
description: Turn your Hass.IO into a Media Player with Docker Service
url: https://github.com/modestpharaoh/hassio-addons/tree/master/remote_speaker
advanced: true
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
audio: true
boot: auto
devices:
  - /dev/shm
  - /dev/snd
init: false
map:
  - media:ro
ports:
  5005/tcp: 5005
ports_description:
  5005/tcp: Rest-API Port
schema: false
stage: experimental
startup: services
